### ISSUE TITLE
How to show error message

### ISSUE THREAD

**Issue by JoeKaris** [apexutils/Execute-PL-SQL-Code#1]
Dear @apexutils ,

Very thanks for your plugin , can you explain how to show error message ?

Best Regards,
Joe Karis

**Comment by apexutils** [comment]
Hi

Sorry for the late reply, but I'm afraid I don't understant the question. 
Provide any value in the "Error Message" attribute, and as long as the PL/SQL block will raise an unhandled exception, that error message will show.

Or is it not working in your case?
